### ISSUE TITLE
Dictionary numbering and alphabet

### ISSUE THREAD

**Issue by sande570** [sande570/Moro-database#18]
1. Change dictionary "showing 1-50" numbers to reflect the actual number of entries on a page (i.e. after a search with only 4 results it should say "showing 1-4").
2. Clicking on a letter should take you OUT of a search result and back to that letter in the full main dictionary.

**Comment by ghost** [comment]
Is this issue completed already?

**Comment by sande570** [comment]
The first half is, but the alphabetization isn't quite right yet. I plan to relook at clicking on the alphabet after searching.

**Comment by ghost** [comment]
I think I have an idea. Lets talk more tomorrow.
